yolo_model:

  config_file:
    #name: yolov3-tiny-obj.cfg
    name: yolov3_testing.cfg
  weight_file:
    #name: yolov3-tiny-obj_last20.weights
    name: yolov3_training_3000.weights
  threshold:
    value: 0.25
  detection_classes:
    names:
      - probe
